// Every SEO surface this page has, in one file.
//
// It is safe to write the head in `+page.svelte` here, unlike in the parent project:
// `+layout.ts` sets `ssr = true` and `prerender = true`, so `<svelte:head>` is rendered
// into the built `index.html` and a crawler that executes no JavaScript still sees the
// title, the description, the card and the JSON-LD. The parent has `ssr = false` and had
// to move all of this into `app.html` — if that ever changes here, this moves with it.
//
// The figures in the copy below are the corpus the firmware actually ships: 2423 species,
// 12724 syllables, 2442 songs. `tools/make_og_card.py` reads them out of the generated
// headers rather than repeating them, so the card cannot drift; this file is the one place
// they are typed by hand, and they are checked in README.md and HANDOFF.md.

export const SITE_URL = 'https://m5lyrebird.variable.gallery';
// The canonical link and og:url carry the trailing slash, because that is the address the
// server actually serves and the one robots.txt and sitemap.xml name. `SITE_URL` without
// it is the origin the JSON-LD `@id`s are built from (`.../#artist`).
export const CANONICAL_URL = `${SITE_URL}/`;
export const SITE_NAME = 'Lyrebird for M5Stack';
export const SITE_TITLE = 'Lyrebird for M5Stack — a bird chorus you flash from the browser';
export const SITE_LOCALE = 'en_GB';

export const SITE_DESCRIPTION =
    'A birdsong synthesizer for the M5Stack Fire and CoreS3. 2423 songbird species, ' +
    '12724 syllables, synthesized on the device by a physical model of the avian ' +
    'syrinx — no samples, no SD card. It boots into a dawn chorus that rolls through ' +
    'the corpus twelve species at a time, and steps down to one species alone. Plug ' +
    'the board in and flash it from this page over Web Serial.';

// Written for the two audiences that read this: someone searching for the boards or the
// technique, and a language model summarising the project from the page. Entities first —
// the boards, the model, the parent work — because those are what either one matches on.
export const SITE_KEYWORDS =
    'lyrebird, birdsong synthesis, syrinx model, Mindlin-Laje oscillator, ' +
    'physical modelling synthesis, bioacoustics, M5Stack, M5Stack Fire, M5Stack CoreS3, ' +
    'ESP32, ESP32-S3, web serial, esp web tools, web installer, firmware flasher, ' +
    'PlatformIO, M5Unified, generative audio, embedded audio, DSP, creative coding, ' +
    'media art, Shahab Nedaei, variable.gallery';

export const ARTIST = {
    name: 'Shahab Nedaei',
    url: 'https://shahabnedaei.variable.gallery',
    sameAs: ['https://github.com/sha5b']
};

// The browser instrument this firmware is a port of. The link goes to the live site
// rather than the repository — that is where the work is, and this page borrows its
// ground (see app.css). REPO_URL below is this project's own source.
export const PARENT_PROJECT = {
    name: 'Lyrebird for the browser',
    url: 'https://lyrebird.variable.gallery'
};

export const REPO_URL = 'https://github.com/sha5b/M5Stack-Lyrebird';

export const LICENCE = {
    name: 'CC BY-NC-SA 4.0',
    url: 'https://creativecommons.org/licenses/by-nc-sa/4.0/'
};

// Generated by tools/make_og_card.py, so its figures come from the shipped headers.
export const OG_IMAGE = `${SITE_URL}/og-card.png`;
export const OG_IMAGE_WIDTH = 1200;
export const OG_IMAGE_HEIGHT = 630;
export const OG_IMAGE_ALT =
    'The Lyrebird mark — a bifurcating syrinx — beside the project name on a sheet of ' +
    'faintly ruled paper, with its figures: 2423 species, 12724 syllables, 2442 songs, ' +
    'flashed from the browser.';

// The clip of both boards, in web/static/. Recorded on a desk, so it is the one asset here
// that is evidence rather than description — which is also why it is the `og:video`: a
// social card that plays 28 seconds of the thing beats one that describes it.
export const VIDEO = {
    url: `${SITE_URL}/lyrebird-boards.mp4`,
    type: 'video/mp4',
    width: 1280,
    height: 720,
    duration: 28,
    poster: `${SITE_URL}/lyrebird-boards-poster.jpg`,
    alt: 'A red M5Stack Fire and a grey CoreS3 side by side on a desk, both showing ALL BIRDS '
        + 'and a thread of pale dots drawing itself across a dark band as a bird sings.'
};

/**
 * One `@graph` rather than several disconnected blocks, so the artist, the page, the
 * firmware and the work it ports are stated as one set of entities whose `@id`s point at
 * each other. That relatedness is the part a knowledge graph can use; separate snippets
 * about the same thing are separate guesses at it.
 *
 * `SoftwareSourceCode` earns its place: what a visitor leaves with is a binary built from
 * this repository, and that is the type which says so — with the boards it runs on in
 * `runtimePlatform` and the licence attached.
 *
 * Deliberately absent: `aggregateRating`, `review`, `offers`, and any DOI. Nothing here is
 * sold or rated, and a knowledge graph believes a wrong identifier.
 */
export function jsonLd(): string {
    return JSON.stringify({
        '@context': 'https://schema.org',
        '@graph': [
            {
                '@type': 'Person',
                '@id': `${SITE_URL}/#artist`,
                name: ARTIST.name,
                url: ARTIST.url,
                sameAs: ARTIST.sameAs
            },
            {
                '@type': 'WebSite',
                '@id': `${SITE_URL}/#website`,
                url: CANONICAL_URL,
                name: SITE_NAME,
                description: SITE_DESCRIPTION,
                inLanguage: 'en-GB',
                author: { '@id': `${SITE_URL}/#artist` },
                publisher: { '@id': `${SITE_URL}/#artist` }
            },
            {
                '@type': 'WebApplication',
                '@id': `${SITE_URL}/#app`,
                url: CANONICAL_URL,
                name: SITE_NAME,
                description: SITE_DESCRIPTION,
                applicationCategory: 'DeveloperApplication',
                operatingSystem: 'Any browser with Web Serial (Chrome, Edge, Opera)',
                browserRequirements: 'Requires the Web Serial API',
                isAccessibleForFree: true,
                isPartOf: { '@id': `${SITE_URL}/#website` },
                author: { '@id': `${SITE_URL}/#artist` },
                isBasedOn: PARENT_PROJECT.url,
                about: { '@id': `${SITE_URL}/#firmware` },
                featureList: [
                    'Flashes an M5Stack Fire or CoreS3 over Web Serial',
                    'Reads the chip off the board and picks the matching image',
                    'No samples: 2423 species are synthesized on the device'
                ],
                image: OG_IMAGE,
                video: {
                    '@type': 'VideoObject',
                    name: 'Lyrebird on an M5Stack Fire and a CoreS3',
                    description: VIDEO.alt,
                    contentUrl: VIDEO.url,
                    thumbnailUrl: VIDEO.poster,
                    encodingFormat: VIDEO.type,
                    width: VIDEO.width,
                    height: VIDEO.height
                }
            },
            {
                '@type': 'SoftwareSourceCode',
                '@id': `${SITE_URL}/#firmware`,
                name: 'Lyrebird firmware for M5Stack',
                description:
                    'Firmware for the M5Stack Fire (ESP32) and CoreS3 (ESP32-S3). A ' +
                    'float32 port of the Mindlin–Laje syrinx model with the whole ' +
                    'Lyrebird corpus — 2423 species, 12724 syllables, 2442 songs — ' +
                    'compiled in as PROGMEM tables.',
                codeRepository: REPO_URL,
                programmingLanguage: ['C++', 'Python', 'TypeScript'],
                runtimePlatform: ['ESP32', 'ESP32-S3', 'Arduino', 'M5Unified'],
                author: { '@id': `${SITE_URL}/#artist` },
                isBasedOn: PARENT_PROJECT.url,
                license: LICENCE.url
            }
        ]
    });
}
