// Generated by tools/generate_assets.py — do not edit.
// Source: assets/inventory.json (Lyrebird authored inventory, CC BY-NC-SA 4.0).
#pragma once
#include <stdint.h>

struct ContourPoint { float t; float hz; };

struct SyllableData {
    float dur;        // seconds
    float level;      // 0..1
    uint8_t timbre;   // 0 pure, 1 reed, 2 buzz
    uint8_t hold;     // sustain instead of decay
    uint8_t two;      // second syringeal side, detuned +7 cents
    float attack;     // seconds; 0 = synth default
    float harmonic;   // 2*f0 tract band gain, 0 = off
    float am;         // AM rate Hz, 0 = off
    float amDepth;
    float vibRate;    // Hz, 0 = off
    float vibDepth;
    uint8_t nContour;
    const ContourPoint* contour;
};

struct SongData {
    uint8_t n;
    const uint8_t* syllIdx;  // n indices into the species' syllables
    const float* gaps;       // n-1 inter-syllable gaps, seconds
};

struct SpeciesData {
    const char* common;
    uint8_t nSyllables;
    const SyllableData* syllables;
    uint8_t nSongs;
    const SongData* songs;
};

static const ContourPoint cont_parus_minor_0[] = {{0.0f, 4200.0f}, {0.35f, 5600.0f}, {1.0f, 4400.0f}};
static const ContourPoint cont_parus_minor_1[] = {{0.0f, 5200.0f}, {0.5f, 4300.0f}, {1.0f, 5000.0f}};
static const ContourPoint cont_parus_minor_2[] = {{0.0f, 3600.0f}, {0.6f, 4900.0f}, {1.0f, 3800.0f}};
static const ContourPoint cont_parus_minor_3[] = {{0.0f, 3000.0f}, {0.5f, 3200.0f}, {1.0f, 2600.0f}};
static const ContourPoint cont_parus_minor_4[] = {{0.0f, 2400.0f}, {0.5f, 2800.0f}, {1.0f, 2200.0f}};
static const ContourPoint cont_parus_minor_5[] = {{0.0f, 4600.0f}, {0.25f, 5200.0f}, {0.5f, 3500.0f}, {1.0f, 3300.0f}};

static const SyllableData syl_parus_minor[] = {
    {0.09f, 0.85f, 0, 0, 0, 0.006f, 0.0f, 0.0f, 0.5f, 0.0f, 0.0f, 3, cont_parus_minor_0}, /* A */
    {0.08f, 0.8f, 0, 0, 0, 0.005f, 0.0f, 0.0f, 0.5f, 0.0f, 0.0f, 3, cont_parus_minor_1}, /* B */
    {0.1f, 0.82f, 1, 0, 0, 0.0f, 0.25f, 0.0f, 0.5f, 0.0f, 0.0f, 3, cont_parus_minor_2}, /* C */
    {0.14f, 0.95f, 2, 0, 0, 0.0f, 0.4f, 95.0f, 0.55f, 0.0f, 0.0f, 3, cont_parus_minor_3}, /* D */
    {0.18f, 0.9f, 2, 0, 0, 0.0f, 0.55f, 60.0f, 0.7f, 0.0f, 0.0f, 3, cont_parus_minor_4}, /* jar */
    {0.13f, 0.9f, 0, 0, 1, 0.0f, 0.0f, 0.0f, 0.5f, 0.0f, 0.0f, 4, cont_parus_minor_5}, /* tsupi */
};

static const uint8_t seq_parus_minor_0[] = {0, 1, 2};
static const float gaps_parus_minor_0[] = {0.05f, 0.05f};
static const uint8_t seq_parus_minor_1[] = {3, 3};
static const float gaps_parus_minor_1[] = {0.07f};
static const uint8_t seq_parus_minor_2[] = {0, 1, 2, 3};
static const float gaps_parus_minor_2[] = {0.05f, 0.05f, 0.11f};
static const uint8_t seq_parus_minor_3[] = {3, 0, 1, 2};
static const float gaps_parus_minor_3[] = {0.11f, 0.05f, 0.05f};
static const uint8_t seq_parus_minor_4[] = {5, 5, 5};
static const float gaps_parus_minor_4[] = {0.12f, 0.12f};
static const SongData songs_parus_minor[] = {
    {3, seq_parus_minor_0, gaps_parus_minor_0},
    {2, seq_parus_minor_1, gaps_parus_minor_1},
    {4, seq_parus_minor_2, gaps_parus_minor_2},
    {4, seq_parus_minor_3, gaps_parus_minor_3},
    {3, seq_parus_minor_4, gaps_parus_minor_4},
};

static const ContourPoint cont_poecile_atricapillus_0[] = {{0.0f, 3400.0f}, {0.4f, 3900.0f}, {1.0f, 3200.0f}};
static const ContourPoint cont_poecile_atricapillus_1[] = {{0.0f, 3100.0f}, {1.0f, 2700.0f}};
static const ContourPoint cont_poecile_atricapillus_2[] = {{0.0f, 2600.0f}, {0.5f, 2900.0f}, {1.0f, 2400.0f}};
static const ContourPoint cont_poecile_atricapillus_3[] = {{0.0f, 2000.0f}, {0.5f, 2100.0f}, {1.0f, 1900.0f}};
static const ContourPoint cont_poecile_atricapillus_4[] = {{0.0f, 4200.0f}, {0.34f, 4150.0f}, {0.4f, 3450.0f}, {1.0f, 3400.0f}};

static const SyllableData syl_poecile_atricapillus[] = {
    {0.07f, 0.8f, 0, 0, 0, 0.004f, 0.0f, 0.0f, 0.5f, 0.0f, 0.0f, 3, cont_poecile_atricapillus_0}, /* chickA */
    {0.06f, 0.75f, 0, 0, 0, 0.0f, 0.0f, 0.0f, 0.5f, 0.0f, 0.0f, 2, cont_poecile_atricapillus_1}, /* chickB */
    {0.08f, 0.8f, 1, 0, 0, 0.0f, 0.3f, 0.0f, 0.5f, 0.0f, 0.0f, 3, cont_poecile_atricapillus_2}, /* chickC */
    {0.12f, 0.95f, 2, 0, 0, 0.0f, 0.6f, 55.0f, 0.6f, 0.0f, 0.0f, 3, cont_poecile_atricapillus_3}, /* chickD */
    {0.5f, 0.9f, 0, 0, 1, 0.0f, 0.0f, 0.0f, 0.5f, 0.0f, 0.0f, 4, cont_poecile_atricapillus_4}, /* feebee */
};

static const uint8_t seq_poecile_atricapillus_0[] = {0, 1, 3, 3};
static const float gaps_poecile_atricapillus_0[] = {0.04f, 0.05f, 0.06f};
static const uint8_t seq_poecile_atricapillus_1[] = {0, 1, 2, 3, 3, 3, 3};
static const float gaps_poecile_atricapillus_1[] = {0.04f, 0.04f, 0.05f, 0.06f, 0.06f, 0.06f};
static const uint8_t seq_poecile_atricapillus_2[] = {4};
static const float gaps_poecile_atricapillus_2[] = {};
static const SongData songs_poecile_atricapillus[] = {
    {4, seq_poecile_atricapillus_0, gaps_poecile_atricapillus_0},
    {7, seq_poecile_atricapillus_1, gaps_poecile_atricapillus_1},
    {1, seq_poecile_atricapillus_2, gaps_poecile_atricapillus_2},
};

static const ContourPoint cont_perisoreus_infaustus_0[] = {{0.0f, 2200.0f}, {0.5f, 2450.0f}, {1.0f, 2150.0f}};
static const ContourPoint cont_perisoreus_infaustus_1[] = {{0.0f, 2600.0f}, {0.4f, 3400.0f}, {1.0f, 2500.0f}};
static const ContourPoint cont_perisoreus_infaustus_2[] = {{0.0f, 4200.0f}, {0.3f, 5200.0f}, {1.0f, 3000.0f}};

static const SyllableData syl_perisoreus_infaustus[] = {
    {0.22f, 0.85f, 1, 0, 0, 0.0f, 0.35f, 0.0f, 0.5f, 0.0f, 0.0f, 3, cont_perisoreus_infaustus_0}, /* hawkPerched */
    {0.16f, 0.9f, 2, 0, 0, 0.0f, 0.45f, 38.0f, 0.5f, 0.0f, 0.0f, 3, cont_perisoreus_infaustus_1}, /* hawkSearching */
    {0.11f, 1.0f, 2, 0, 0, 0.0f, 0.7f, 120.0f, 0.8f, 0.0f, 0.0f, 3, cont_perisoreus_infaustus_2}, /* hawkAttacking */
};

static const uint8_t seq_perisoreus_infaustus_0[] = {0, 0};
static const float gaps_perisoreus_infaustus_0[] = {0.3f};
static const uint8_t seq_perisoreus_infaustus_1[] = {2, 2, 2, 2};
static const float gaps_perisoreus_infaustus_1[] = {0.07f, 0.07f, 0.07f};
static const SongData songs_perisoreus_infaustus[] = {
    {2, seq_perisoreus_infaustus_0, gaps_perisoreus_infaustus_0},
    {4, seq_perisoreus_infaustus_1, gaps_perisoreus_infaustus_1},
};

static const ContourPoint cont_lonchura_striata_0[] = {{0.0f, 1800.0f}, {0.4f, 3200.0f}, {1.0f, 2400.0f}};
static const ContourPoint cont_lonchura_striata_1[] = {{0.0f, 3800.0f}, {1.0f, 2600.0f}};
static const ContourPoint cont_lonchura_striata_2[] = {{0.0f, 2600.0f}, {0.3f, 5200.0f}, {0.7f, 4600.0f}, {1.0f, 5400.0f}};
static const ContourPoint cont_lonchura_striata_3[] = {{0.0f, 4400.0f}, {0.5f, 3100.0f}, {1.0f, 3600.0f}};
static const ContourPoint cont_lonchura_striata_4[] = {{0.0f, 1600.0f}, {0.5f, 2200.0f}, {1.0f, 1500.0f}};
static const ContourPoint cont_lonchura_striata_5[] = {{0.0f, 6200.0f}, {0.4f, 7200.0f}, {1.0f, 5200.0f}};

static const SyllableData syl_lonchura_striata[] = {
    {0.07f, 0.85f, 1, 0, 1, 0.0f, 0.4f, 0.0f, 0.5f, 0.0f, 0.0f, 3, cont_lonchura_striata_0}, /* a */
    {0.05f, 0.8f, 2, 0, 0, 0.0f, 0.0f, 140.0f, 0.6f, 0.0f, 0.0f, 2, cont_lonchura_striata_1}, /* b */
    {0.09f, 0.9f, 0, 0, 0, 0.0f, 0.0f, 0.0f, 0.5f, 0.0f, 0.0f, 4, cont_lonchura_striata_2}, /* c */
    {0.06f, 0.82f, 1, 0, 0, 0.0f, 0.5f, 0.0f, 0.5f, 0.0f, 0.0f, 3, cont_lonchura_striata_3}, /* d */
    {0.11f, 0.88f, 2, 0, 0, 0.0f, 0.35f, 70.0f, 0.45f, 0.0f, 0.0f, 3, cont_lonchura_striata_4}, /* e */
    {0.08f, 0.86f, 0, 0, 1, 0.0f, 0.0f, 0.0f, 0.5f, 0.0f, 0.0f, 3, cont_lonchura_striata_5}, /* f */
};

static const uint8_t seq_lonchura_striata_0[] = {0, 1, 1, 2, 3, 4, 5, 2};
static const float gaps_lonchura_striata_0[] = {0.03f, 0.03f, 0.04f, 0.03f, 0.04f, 0.03f, 0.04f};
static const SongData songs_lonchura_striata[] = {
    {8, seq_lonchura_striata_0, gaps_lonchura_striata_0},
};

static const ContourPoint cont_taeniopygia_guttata_0[] = {{0.0f, 1000.0f}, {1.0f, 900.0f}};
static const ContourPoint cont_taeniopygia_guttata_1[] = {{0.0f, 700.0f}, {0.4f, 1400.0f}, {1.0f, 900.0f}};
static const ContourPoint cont_taeniopygia_guttata_2[] = {{0.0f, 3200.0f}, {0.5f, 4600.0f}, {1.0f, 3000.0f}};
static const ContourPoint cont_taeniopygia_guttata_3[] = {{0.0f, 2400.0f}, {0.3f, 1800.0f}, {0.6f, 2600.0f}, {1.0f, 1600.0f}};
static const ContourPoint cont_taeniopygia_guttata_4[] = {{0.0f, 550.0f}, {0.2f, 900.0f}, {0.7f, 800.0f}, {1.0f, 620.0f}};

static const SyllableData syl_taeniopygia_guttata[] = {
    {0.045f, 0.6f, 1, 0, 0, 0.0f, 0.5f, 0.0f, 0.5f, 0.0f, 0.0f, 2, cont_taeniopygia_guttata_0}, /* intro */
    {0.09f, 0.9f, 2, 0, 0, 0.0f, 0.6f, 45.0f, 0.55f, 0.0f, 0.0f, 3, cont_taeniopygia_guttata_1}, /* zf1 */
    {0.07f, 0.88f, 0, 0, 1, 0.0f, 0.0f, 0.0f, 0.5f, 0.0f, 0.0f, 3, cont_taeniopygia_guttata_2}, /* zf2 */
    {0.12f, 0.92f, 1, 0, 0, 0.0f, 0.45f, 0.0f, 0.5f, 0.0f, 0.0f, 4, cont_taeniopygia_guttata_3}, /* zf3 */
    {0.16f, 0.95f, 1, 0, 1, 0.0f, 0.65f, 0.0f, 0.5f, 0.0f, 0.0f, 4, cont_taeniopygia_guttata_4}, /* distance */
};

static const uint8_t seq_taeniopygia_guttata_0[] = {0, 0, 0, 1, 2, 3, 1, 2, 3};
static const float gaps_taeniopygia_guttata_0[] = {0.05f, 0.05f, 0.06f, 0.03f, 0.03f, 0.05f, 0.03f, 0.03f};
static const uint8_t seq_taeniopygia_guttata_1[] = {4};
static const float gaps_taeniopygia_guttata_1[] = {};
static const SongData songs_taeniopygia_guttata[] = {
    {9, seq_taeniopygia_guttata_0, gaps_taeniopygia_guttata_0},
    {1, seq_taeniopygia_guttata_1, gaps_taeniopygia_guttata_1},
};

static const ContourPoint cont_horornis_diphone_0[] = {{0.0f, 2050.0f}, {0.6f, 2120.0f}, {1.0f, 2080.0f}};
static const ContourPoint cont_horornis_diphone_1[] = {{0.0f, 2400.0f}, {0.3f, 4200.0f}, {1.0f, 3200.0f}};
static const ContourPoint cont_horornis_diphone_2[] = {{0.0f, 3600.0f}, {0.25f, 2600.0f}, {0.6f, 3400.0f}, {1.0f, 2200.0f}};

static const SyllableData syl_horornis_diphone[] = {
    {0.9f, 0.8f, 0, 1, 0, 0.09f, 0.0f, 0.0f, 0.5f, 0.0f, 0.0f, 3, cont_horornis_diphone_0}, /* ho */
    {0.12f, 0.95f, 0, 0, 1, 0.0f, 0.0f, 0.0f, 0.5f, 0.0f, 0.0f, 3, cont_horornis_diphone_1}, /* ho2 */
    {0.2f, 1.0f, 1, 0, 0, 0.0f, 0.3f, 0.0f, 0.5f, 0.0f, 0.0f, 4, cont_horornis_diphone_2}, /* kyo */
};

static const uint8_t seq_horornis_diphone_0[] = {0, 1, 2};
static const float gaps_horornis_diphone_0[] = {0.16f, 0.03f};
static const SongData songs_horornis_diphone[] = {
    {3, seq_horornis_diphone_0, gaps_horornis_diphone_0},
};

static const ContourPoint cont_turdus_merula_0[] = {{0.0f, 1500.0f}, {0.2f, 2100.0f}, {0.5f, 1750.0f}, {0.8f, 2300.0f}, {1.0f, 1900.0f}};
static const ContourPoint cont_turdus_merula_1[] = {{0.0f, 2200.0f}, {0.3f, 1600.0f}, {0.7f, 2000.0f}, {1.0f, 1400.0f}};
static const ContourPoint cont_turdus_merula_2[] = {{0.0f, 4200.0f}, {0.4f, 5600.0f}, {0.7f, 4800.0f}, {1.0f, 6200.0f}};

static const SyllableData syl_turdus_merula[] = {
    {0.28f, 0.9f, 0, 0, 1, 0.0f, 0.0f, 0.0f, 0.5f, 0.0f, 0.0f, 5, cont_turdus_merula_0}, /* flute1 */
    {0.3f, 0.88f, 0, 0, 0, 0.0f, 0.0f, 0.0f, 0.5f, 0.0f, 0.0f, 4, cont_turdus_merula_1}, /* flute2 */
    {0.22f, 0.6f, 2, 0, 0, 0.0f, 0.4f, 45.0f, 0.5f, 0.0f, 0.0f, 4, cont_turdus_merula_2}, /* twitter */
};

static const uint8_t seq_turdus_merula_0[] = {0, 1, 2};
static const float gaps_turdus_merula_0[] = {0.08f, 0.05f};
static const SongData songs_turdus_merula[] = {
    {3, seq_turdus_merula_0, gaps_turdus_merula_0},
};

static const ContourPoint cont_luscinia_megarhynchos_0[] = {{0.0f, 1650.0f}, {0.5f, 1700.0f}, {1.0f, 1750.0f}};
static const ContourPoint cont_luscinia_megarhynchos_1[] = {{0.0f, 2600.0f}, {0.5f, 3000.0f}, {1.0f, 2500.0f}};
static const ContourPoint cont_luscinia_megarhynchos_2[] = {{0.0f, 900.0f}, {0.4f, 1500.0f}, {1.0f, 1000.0f}};
static const ContourPoint cont_luscinia_megarhynchos_3[] = {{0.0f, 2200.0f}, {0.3f, 3600.0f}, {0.6f, 3000.0f}, {1.0f, 4800.0f}};

static const SyllableData syl_luscinia_megarhynchos[] = {
    {0.34f, 0.95f, 0, 0, 0, 0.05f, 0.0f, 0.0f, 0.5f, 0.0f, 0.0f, 3, cont_luscinia_megarhynchos_0}, /* whistleCrescendo */
    {0.4f, 0.9f, 2, 0, 0, 0.0f, 0.0f, 22.0f, 0.9f, 0.0f, 0.0f, 3, cont_luscinia_megarhynchos_1}, /* sobTrill */
    {0.14f, 1.0f, 1, 0, 0, 0.0f, 0.6f, 0.0f, 0.5f, 0.0f, 0.0f, 3, cont_luscinia_megarhynchos_2}, /* jugJug */
    {0.26f, 0.92f, 0, 0, 1, 0.0f, 0.0f, 0.0f, 0.5f, 0.0f, 0.0f, 4, cont_luscinia_megarhynchos_3}, /* flourish */
};

static const uint8_t seq_luscinia_megarhynchos_0[] = {0, 0, 1, 3};
static const float gaps_luscinia_megarhynchos_0[] = {0.2f, 0.18f, 0.06f};
static const uint8_t seq_luscinia_megarhynchos_1[] = {2, 2, 2, 1};
static const float gaps_luscinia_megarhynchos_1[] = {0.07f, 0.07f, 0.1f};
static const SongData songs_luscinia_megarhynchos[] = {
    {4, seq_luscinia_megarhynchos_0, gaps_luscinia_megarhynchos_0},
    {4, seq_luscinia_megarhynchos_1, gaps_luscinia_megarhynchos_1},
};

static const ContourPoint cont_troglodytes_troglodytes_0[] = {{0.0f, 4200.0f}, {0.3f, 6400.0f}, {0.6f, 5000.0f}, {1.0f, 5800.0f}};
static const ContourPoint cont_troglodytes_troglodytes_1[] = {{0.0f, 5200.0f}, {1.0f, 3600.0f}};

static const SyllableData syl_troglodytes_troglodytes[] = {
    {0.55f, 1.0f, 2, 0, 0, 0.0f, 0.0f, 28.0f, 0.95f, 0.0f, 0.0f, 4, cont_troglodytes_troglodytes_0}, /* wrenTrill */
    {0.05f, 0.9f, 2, 0, 0, 0.0f, 0.0f, 180.0f, 0.7f, 0.0f, 0.0f, 2, cont_troglodytes_troglodytes_1}, /* wrenChip */
};

static const uint8_t seq_troglodytes_troglodytes_0[] = {1, 1, 0};
static const float gaps_troglodytes_troglodytes_0[] = {0.05f, 0.06f};
static const SongData songs_troglodytes_troglodytes[] = {
    {3, seq_troglodytes_troglodytes_0, gaps_troglodytes_troglodytes_0},
};

static const ContourPoint cont_cuculus_canorus_0[] = {{0.0f, 700.0f}, {1.0f, 690.0f}};
static const ContourPoint cont_cuculus_canorus_1[] = {{0.0f, 555.0f}, {1.0f, 545.0f}};

static const SyllableData syl_cuculus_canorus[] = {
    {0.17f, 0.9f, 0, 1, 0, 0.02f, 0.0f, 0.0f, 0.5f, 0.0f, 0.0f, 2, cont_cuculus_canorus_0}, /* cuck */
    {0.24f, 0.8f, 0, 1, 0, 0.03f, 0.0f, 0.0f, 0.5f, 0.0f, 0.0f, 2, cont_cuculus_canorus_1}, /* oo */
};

static const uint8_t seq_cuculus_canorus_0[] = {0, 1};
static const float gaps_cuculus_canorus_0[] = {0.06f};
static const SongData songs_cuculus_canorus[] = {
    {2, seq_cuculus_canorus_0, gaps_cuculus_canorus_0},
};

static const ContourPoint cont_strix_aluco_0[] = {{0.0f, 520.0f}, {0.4f, 540.0f}, {1.0f, 500.0f}};
static const ContourPoint cont_strix_aluco_1[] = {{0.0f, 470.0f}, {0.15f, 560.0f}, {0.7f, 530.0f}, {1.0f, 450.0f}};

static const SyllableData syl_strix_aluco[] = {
    {0.3f, 0.85f, 0, 1, 0, 0.05f, 0.15f, 0.0f, 0.5f, 0.0f, 0.0f, 3, cont_strix_aluco_0}, /* hooFirst */
    {0.95f, 0.95f, 0, 1, 0, 0.06f, 0.2f, 0.0f, 0.5f, 11.0f, 0.035f, 4, cont_strix_aluco_1}, /* hooLong */
};

static const uint8_t seq_strix_aluco_0[] = {0, 1};
static const float gaps_strix_aluco_0[] = {0.55f};
static const SongData songs_strix_aluco[] = {
    {2, seq_strix_aluco_0, gaps_strix_aluco_0},
};

static const ContourPoint cont_zosterops_japonicus_0[] = {{0.0f, 2800.0f}, {0.5f, 4400.0f}, {1.0f, 3600.0f}};
static const ContourPoint cont_zosterops_japonicus_1[] = {{0.0f, 4600.0f}, {0.4f, 3200.0f}, {1.0f, 3800.0f}};
static const ContourPoint cont_zosterops_japonicus_2[] = {{0.0f, 3400.0f}, {1.0f, 2900.0f}};

static const SyllableData syl_zosterops_japonicus[] = {
    {0.1f, 0.85f, 0, 0, 1, 0.0f, 0.0f, 0.0f, 0.5f, 0.0f, 0.0f, 3, cont_zosterops_japonicus_0}, /* warbleUp */
    {0.09f, 0.82f, 1, 0, 0, 0.0f, 0.3f, 0.0f, 0.5f, 0.0f, 0.0f, 3, cont_zosterops_japonicus_1}, /* warbleDown */
    {0.07f, 0.75f, 2, 0, 0, 0.0f, 0.0f, 130.0f, 0.6f, 0.0f, 0.0f, 2, cont_zosterops_japonicus_2}, /* mejiroChirr */
};

static const uint8_t seq_zosterops_japonicus_0[] = {0, 1, 0, 2, 1};
static const float gaps_zosterops_japonicus_0[] = {0.04f, 0.04f, 0.05f, 0.04f};
static const SongData songs_zosterops_japonicus[] = {
    {5, seq_zosterops_japonicus_0, gaps_zosterops_japonicus_0},
};

static const SpeciesData SPECIES[] = {
    {"Japanese great tit", 6, syl_parus_minor, 5, songs_parus_minor},
    {"Black-capped chickadee", 5, syl_poecile_atricapillus, 3, songs_poecile_atricapillus},
    {"Siberian jay", 3, syl_perisoreus_infaustus, 2, songs_perisoreus_infaustus},
    {"Bengalese finch", 6, syl_lonchura_striata, 1, songs_lonchura_striata},
    {"Zebra finch", 5, syl_taeniopygia_guttata, 2, songs_taeniopygia_guttata},
    {"Japanese bush warbler (uguisu)", 3, syl_horornis_diphone, 1, songs_horornis_diphone},
    {"Common blackbird", 3, syl_turdus_merula, 1, songs_turdus_merula},
    {"Common nightingale", 4, syl_luscinia_megarhynchos, 2, songs_luscinia_megarhynchos},
    {"Eurasian wren", 2, syl_troglodytes_troglodytes, 1, songs_troglodytes_troglodytes},
    {"Common cuckoo", 2, syl_cuculus_canorus, 1, songs_cuculus_canorus},
    {"Tawny owl", 2, syl_strix_aluco, 1, songs_strix_aluco},
    {"Japanese white-eye (mejiro)", 3, syl_zosterops_japonicus, 1, songs_zosterops_japonicus},
};

#define SPECIES_COUNT 12
