#!/usr/bin/env python3
"""Generate the firmware's data headers from the vendored Lyrebird assets.

Reads assets/inventory.json (12 authored species) and
assets/syrinx-calibration.json (the offline beta/ampPP tables) and emits:

  include/bird_data.h    — species / songs / syllables as PROGMEM C structs
  include/calibration.h  — the float lookup tables the synth interpolates

Song syllable ids are resolved to indices here, so the firmware never does
string lookups. Re-run only when the vendored assets change:

  python3 tools/generate_assets.py
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TIMBRES = {"pure": 0, "reed": 1, "buzz": 2}
DEFAULT_GAP = 0.06  # engine.ts playSequence's fallback gap


def f32(x):
    """Format a float for a C header, keeping full single-precision round trip."""
    return repr(float(x)) + "f"


def gen_bird_data(inv):
    out = []
    out.append("// Generated by tools/generate_assets.py — do not edit.")
    out.append("// Source: assets/inventory.json (Lyrebird authored inventory, CC BY-NC-SA 4.0).")
    out.append("#pragma once")
    out.append("#include <stdint.h>")
    out.append("")
    out.append("struct ContourPoint { float t; float hz; };")
    out.append("")
    out.append("struct SyllableData {")
    out.append("    float dur;        // seconds")
    out.append("    float level;      // 0..1")
    out.append("    uint8_t timbre;   // 0 pure, 1 reed, 2 buzz")
    out.append("    uint8_t hold;     // sustain instead of decay")
    out.append("    uint8_t two;      // second syringeal side, detuned +7 cents")
    out.append("    float attack;     // seconds; 0 = synth default")
    out.append("    float harmonic;   // 2*f0 tract band gain, 0 = off")
    out.append("    float am;         // AM rate Hz, 0 = off")
    out.append("    float amDepth;")
    out.append("    float vibRate;    // Hz, 0 = off")
    out.append("    float vibDepth;")
    out.append("    uint8_t nContour;")
    out.append("    const ContourPoint* contour;")
    out.append("};")
    out.append("")
    out.append("struct SongData {")
    out.append("    uint8_t n;")
    out.append("    const uint8_t* syllIdx;  // n indices into the species' syllables")
    out.append("    const float* gaps;       // n-1 inter-syllable gaps, seconds")
    out.append("};")
    out.append("")
    out.append("struct SpeciesData {")
    out.append("    const char* common;")
    out.append("    uint8_t nSyllables;")
    out.append("    const SyllableData* syllables;")
    out.append("    uint8_t nSongs;")
    out.append("    const SongData* songs;")
    out.append("};")
    out.append("")

    species_syms = []
    for sp in inv["species"]:
        sid = sp["id"]
        syl_syms = []
        for i, sy in enumerate(sp["syllables"]):
            sym = f"cont_{sid}_{i}"
            pts = ", ".join("{%s, %s}" % (f32(t), f32(hz)) for t, hz in sy["contour"])
            out.append(f"static const ContourPoint {sym}[] = {{{pts}}};")
            syl_syms.append(sym)
        out.append("")
        for i, sy in enumerate(sp["syllables"]):
            vib = sy.get("vib") or {}
            syl_syms[i] = (
                "{%s, %s, %d, %d, %d, %s, %s, %s, %s, %s, %s, %d, %s}, /* %s */" % (
                    f32(sy["dur"]),
                    f32(sy["level"]),
                    TIMBRES[sy.get("timbre", "pure")],
                    1 if sy.get("hold") else 0,
                    1 if sy.get("two") else 0,
                    f32(sy.get("attack", 0)),
                    f32(sy.get("harmonic", 0)),
                    f32(sy.get("am", 0)),
                    f32(sy.get("amDepth", 0.5)),
                    f32(vib.get("rate", 0)),
                    f32(vib.get("depth", 0)),
                    len(sy["contour"]),
                    syl_syms[i],
                    sy["id"],
                )
            )
        out.append(f"static const SyllableData syl_{sid}[] = {{")
        for entry in syl_syms:
            out.append(f"    {entry}")
        out.append("};")
        out.append("")

        id_to_idx = {sy["id"]: i for i, sy in enumerate(sp["syllables"])}
        song_entries = []
        for j, so in enumerate(sp["songs"]):
            seq = [id_to_idx[x] for x in so["sequence"]]
            gaps = list(so["gaps"])
            while len(gaps) < len(seq) - 1:
                gaps.append(DEFAULT_GAP)
            out.append(
                f"static const uint8_t seq_{sid}_{j}[] = {{{', '.join(str(x) for x in seq)}}};"
            )
            out.append(
                f"static const float gaps_{sid}_{j}[] = {{{', '.join(f32(g) for g in gaps)}}};"
            )
            song_entries.append("{%d, seq_%s_%d, gaps_%s_%d}" % (len(seq), sid, j, sid, j))
        out.append(f"static const SongData songs_{sid}[] = {{")
        for entry in song_entries:
            out.append(f"    {entry},")
        out.append("};")
        out.append("")
        species_syms.append((sp["common"], sid, len(sp["syllables"]), len(sp["songs"])))

    out.append("static const SpeciesData SPECIES[] = {")
    for common, sid, nsyl, nsong in species_syms:
        out.append(
            '    {"%s", %d, syl_%s, %d, songs_%s},' % (common, nsyl, sid, nsong, sid)
        )
    out.append("};")
    out.append("")
    out.append("#define SPECIES_COUNT %d" % len(species_syms))
    return "\n".join(out) + "\n"


def gen_calibration(cal):
    out = []
    out.append("// Generated by tools/generate_assets.py — do not edit.")
    out.append("// Source: assets/syrinx-calibration.json (Lyrebird offline tables, CC BY-NC-SA 4.0).")
    out.append("#pragma once")
    out.append("")

    def emit_1d(name, values):
        out.append(f"static const int {name.upper()}_LEN = {len(values)};")
        out.append(f"static const float {name}[{len(values)}] = {{")
        for i in range(0, len(values), 8):
            out.append("    " + ", ".join(f32(v) for v in values[i : i + 8]) + ",")
        out.append("};")
        out.append("")

    def emit_2d(name, rows):
        out.append(f"static const float {name}[{len(rows)}][{len(rows[0])}] = {{")
        for row in rows:
            out.append("    {")
            for i in range(0, len(row), 8):
                out.append("        " + ", ".join(f32(v) for v in row[i : i + 8]) + ",")
            out.append("    },")
        out.append("};")
        out.append("")

    emit_1d("CAL_PRESSURE_GRID", cal["pressureGrid"])
    emit_1d("CAL_BETA_GRID", cal["betaGrid"])
    emit_1d("CAL_INV_F0_GRID", cal["inverse"]["f0Grid"])
    emit_2d("CAL_INV_BETA", cal["inverse"]["beta"])
    emit_2d("CAL_AMP_PP", cal["ampPP"])
    out.append("static const float CAL_BETA_MIN = %s;" % f32(cal["betaClamp"][0]))
    out.append("static const float CAL_BETA_MAX = %s;" % f32(cal["betaClamp"][1]))
    return "\n".join(out) + "\n"


def main():
    with open(os.path.join(ROOT, "assets", "inventory.json")) as f:
        inv = json.load(f)
    with open(os.path.join(ROOT, "assets", "syrinx-calibration.json")) as f:
        cal = json.load(f)

    bird = gen_bird_data(inv)
    with open(os.path.join(ROOT, "include", "bird_data.h"), "w") as f:
        f.write(bird)
    calib = gen_calibration(cal)
    with open(os.path.join(ROOT, "include", "calibration.h"), "w") as f:
        f.write(calib)

    print("bird_data.h: %d species, %d syllables, %d songs, %.1f KB" % (
        len(inv["species"]),
        sum(len(s["syllables"]) for s in inv["species"]),
        sum(len(s["songs"]) for s in inv["species"]),
        len(bird) / 1024,
    ))
    print("calibration.h: %.1f KB" % (len(calib) / 1024))


if __name__ == "__main__":
    main()
